SERIAL_PERIPHERAL : /dev/serial0
NUM_BAGS_PER_COL : 33
NUM_BAGS_IN_BUFFER : 10
NUM_COLS : 3
START_POS : 6
PUSHED_POS : 10
STAGE_POS : 31.41592 # 10*pi
BAG_WIDTH : 0.4

GRIPPER1_SOL_PIN : 1
GRIPPER2_SOL_PIN : 2
GRIPPER3_SOL : 3

